### ISSUE TITLE
Tracing Plugin looks a little crowded

### ISSUE THREAD

**Issue by DerekStride** [GraphQL-Query-Planner/graphiql-plugins#2]
I made the following query and it made the tracing plugin look a little crowded. Also the bottom of the pane has a bunch of wasted space.

```graphql
query {
  nodes(ids: ["gid://webscale/User/1", "gid://webscale/User/2"]) {
    id
  }
  like(user_id: 1, content_id: 373) {
    __typename
  }
  search(query: "Televizzle") {
    id
    score
    index
    type
    record {
      __typename
    }
  }
}
```

<img width="810" alt="screenshot 2018-03-13 20 56 27" src="https://user-images.githubusercontent.com/6456191/37377563-08d5736a-2701-11e8-8a45-a7013fef7276.png">

**Comment by ismail-syed** [comment]
I've make a couple tweaks to improve this but you'll still see this cluttering in cases where a lot of data is being returned and the provided chart tab doesn't have enough real estate to show it. I've make some improves to the pane resizing so try it out and give it a shot. 

For this query
```
{
  node(id: "gid://webscale/User/1") {
    id
    ...on User {
      first_name
      posts {
        id
        receiver {
          first_name
        }
      }
    }
  }
}
```

An initial render on a small panel renders this

<img width="614" alt="screen shot 2018-03-14 at 1 02 59 am" src="https://user-images.githubusercontent.com/6130700/37384207-dabbfb20-2723-11e8-9fe0-83adde36a150.png">

Using the panel bars, you can resize it and it'll look something like: 

<img width="1273" alt="screen shot 2018-03-14 at 1 03 18 am" src="https://user-images.githubusercontent.com/6130700/37384223-f04081b4-2723-11e8-870d-7419d5bb295a.png">



There's only soo much we can do here. If we care deeply about this, we can add a view that says, `Please expand the tab to view the chart`, then render the chart if the size is big. Given that apollo-tracing work was a nice to have, we should be good to stop here. 

Test it out again and lemme know what you think.

**Comment by DerekStride** [comment]
Could be have a scrollbar?

**Comment by ismail-syed** [comment]
there's already a scrollbar

**Comment by ismail-syed** [comment]
there's already a scrollbar

**Comment by ismail-syed** [comment]
Fixed by https://github.com/GraphQL-Query-Planner/graphiql-plugins/commit/ae9eb7171e154bb8fe081ce26e39c5f164b83d87

IRL we decided to hide the labels if we have too many resolvers.
